# Generated by Django 3.1.8 on 2023-08-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='creator',
            new_name='User',
        ),
    ]
