# Generated by Django 4.2.3 on 2023-08-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='Faculty',
            field=models.ManyToManyField(null=True, to='faculty.faculty'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='age',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='faculty.department'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
