# Generated by Django 4.2.4 on 2023-08-08 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_professor_faculty_alter_professor_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='Faculty',
        ),
        migrations.AlterField(
            model_name='professor',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='Faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='faculty.faculty'),
        ),
    ]
