# Generated by Django 4.2.4 on 2023-08-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_remove_professor_faculty_alter_professor_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='Faculty',
        ),
        migrations.AddField(
            model_name='professor',
            name='Faculty',
            field=models.ManyToManyField(null=True, to='faculty.faculty'),
        ),
    ]
