# Generated by Django 4.2.4 on 2023-08-08 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_subjects_remove_professor_faculty_professor_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='Faculty',
        ),
        migrations.AddField(
            model_name='professor',
            name='Faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='faculty.faculty'),
        ),
    ]
